// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG2gAkm--nWzNkyUoeoVARw7UBqW5uHUQ',
    appId: '1:904714114278:web:5f5deb4d81c8abe996d727',
    messagingSenderId: '904714114278',
    projectId: 're-exam-90684',
    authDomain: 're-exam-90684.firebaseapp.com',
    storageBucket: 're-exam-90684.appspot.com',
    measurementId: 'G-B8VV9PREWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFRUwj8iy5ID2x77u80mD-YJUjh_gDPtc',
    appId: '1:904714114278:android:94ef994904cbb0a496d727',
    messagingSenderId: '904714114278',
    projectId: 're-exam-90684',
    storageBucket: 're-exam-90684.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkhznIl_83yFVW-kPCgK13YCSMueCV7Ew',
    appId: '1:904714114278:ios:e857e60d84ee203296d727',
    messagingSenderId: '904714114278',
    projectId: 're-exam-90684',
    storageBucket: 're-exam-90684.appspot.com',
    iosBundleId: 'com.example.advanceFinalExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkhznIl_83yFVW-kPCgK13YCSMueCV7Ew',
    appId: '1:904714114278:ios:e857e60d84ee203296d727',
    messagingSenderId: '904714114278',
    projectId: 're-exam-90684',
    storageBucket: 're-exam-90684.appspot.com',
    iosBundleId: 'com.example.advanceFinalExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG2gAkm--nWzNkyUoeoVARw7UBqW5uHUQ',
    appId: '1:904714114278:web:de2204cc4a262c8b96d727',
    messagingSenderId: '904714114278',
    projectId: 're-exam-90684',
    authDomain: 're-exam-90684.firebaseapp.com',
    storageBucket: 're-exam-90684.appspot.com',
    measurementId: 'G-SNVNCBSDPQ',
  );
}
